name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
      minecraft_version:
        description: 'Minecraft version to release for (e.g., 1.20.4)'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --stacktrace -Pmod_version=${{ github.event.inputs.version }}

      - name: Publish to Modrinth/GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          loaders: fabric
          version-type: alpha
          game-versions: ${{ github.event.inputs.minecraft_version }}
          version: ${{ github.event.inputs.version }}

          modrinth-id: O1NqR8b2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-prerelease: true
          github-tag: v${{ github.event.inputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ github.event.inputs.version }}
          path: |
            build/libs/*.jar
